#!/bin/bash
#$ -cwd
#$ -S /bin/bash
#$ -N Opt_3400
#$ -l h_vmem=10G
# -l s_rt=00:00:40	# hh::mm::ss
#$ -pe threaded 8

echo Starting job

export OMP_NUM_THREADS=$NSLOTS
./noname 50001 1 300

echo Finishing job
#touch AUTO_RESTART_PLEASE
#qsub script
